name: glyph
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.1+2

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.6.0
  flutter_local_notifications: ^17.2.4
  file_picker: ^8.1.7
  record: ^6.1.1
  path_provider: ^2.1.5
  path: ^1.9.0
  audioplayers: ^6.1.0
  dio: ^5.7.0
  flutter_gemma: ^0.14.5
  sqflite: ^2.4.2+1
  fl_chart: ^1.2.0
  growth_standards: ^4.4.1
  share_plus: ^12.0.2
  flutter_tts: ^4.2.5
  super_measurement: ^4.0.0
  wake_on_lan: ^4.1.1
  qr_flutter: ^4.1.0
  speech_to_text: ^7.3.0
  google_mlkit_image_labeling: ^0.14.2
  google_mlkit_text_recognition: ^0.15.1
  google_mlkit_object_detection: ^0.15.1
  permission_handler: ^12.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: false
  ios: "AppIcon"
  image_path: "assets/logo.png"
  remove_alpha_ios: true
  web:
    generate: true
    image_path: "assets/logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/wayuu_dictionary.json
    - assets/world.geo.json
    - assets/wayuu_sano.mp3
    - assets/wayuu_peligro.mp3
    - assets/wayuu_precaucion.mp3
