name: "CI - Glyph Mobile"
on:
  workflow_dispatch:

jobs:
  build:
    name: Compilando en macOS
    runs-on: macos-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4 # Actualizado a v4

      - name: Instalar Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Generar Iconos y Preparar Dependencias
        run: |
          # Limpieza profunda de archivos que causan errores de ruta en CI
          flutter clean
          rm -rf ios/Flutter/Generated.xcconfig
          rm -rf ios/Flutter/flutter_export_environment.sh
          flutter pub get
          
          # Asegurar que el Bundle ID sea el correcto en el proyecto de Xcode
          sed -i '' 's/com.example.myapp/com.glyph.app/g' ios/Runner.xcodeproj/project.pbxproj
          
          # Desactivar el sandboxing de scripts (necesario para Xcode 15+)
          echo "ENABLE_USER_SCRIPT_SANDBOXING = NO" >> ios/Flutter/Generated.xcconfig
          
          dart run flutter_launcher_icons

      - name: Crear App sin firma
        run: |
          # Compilación forzando la omisión de firma de código
          flutter build ios --release --no-codesign \
            --build-name=1.0.0 --build-number=1 \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGN_ENTITLEMENTS="" \
            CODE_SIGNING_METHOD=manual
          
          # Empaquetado manual en formato IPA
          mkdir -p Payload
          cp -r build/ios/iphoneos/Runner.app Payload/
          zip -r mi_aplicacion.ipa Payload/

      - name: Guardar archivo final
        uses: actions/upload-artifact@v4
        with:
          name: app-bundle
          path: mi_aplicacion.ipa
